name: Build Release

on: 
  workflow_dispatch:
  push:
    tags: "v*"

env:
  packageName: "net.gatosyocora.meshdeleterwithtexture"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: get tag
        id: tag
        run: echo ${GITHUB_REF##*/}
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=MeshDeleterWithTexture_${{ steps.tag.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=MeshDeleterWithTexture_${{ steps.tag.outputs.prop }}.unitypackage" >> $GITHUB_ENV
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "Packages/${{env.packageName}}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
          
      - run: find "Packages/${{env.packageName}}/" -name \*.meta >> metaList
          
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - name: version
        id: version
        run: echo "${{ steps.tag.outputs.prop }}" | sed -e "s/v//g" >> $GITHUB_ENV
        
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          name: ${{ steps.tag.version.prop }}
          tag_name: ${{ steps.tag.outputs.prop }}
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            Packages/${{ env.packageName }}/package.json
